/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.model;

import java.util.Date;

import com.hyetec.uap.core.model.IdLong;

public class Enterprise extends IdLong {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.pk_id
	 *
	 * @hyetec
	 */
	private Long pkId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.user_id
	 *
	 * @hyetec
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.name
	 *
	 * @hyetec
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.registered_capital
	 *
	 * @hyetec
	 */
	private String registeredCapital;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.corporation
	 *
	 * @hyetec
	 */
	private String corporation;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.address
	 *
	 * @hyetec
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.permission
	 *
	 * @hyetec
	 */
	private Long permission;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.introduction
	 *
	 * @hyetec
	 */
	private String introduction;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.brief
	 *
	 * @hyetec
	 */
	private String brief;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.level
	 *
	 * @hyetec
	 */
	private Long level;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.status
	 *
	 * @hyetec
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_enterprise.create_time
	 *
	 * @hyetec
	 */
	private Date createTime;

	private String creditNumber;

	private String listingCode;
	
	//企业咨询侧重点
	private String advices;

	// 估值次数
	private Integer times;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.pk_id
	 *
	 * @return the value of f_enterprise.pk_id
	 *
	 * @hyetec
	 */
	public Long getPkId() {
		return pkId;
	}

	public String getAdvices() {
		return advices;
	}

	public void setAdvices(String advices) {
		this.advices = advices;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.pk_id
	 *
	 * @param pkId
	 *            the value for f_enterprise.pk_id
	 *
	 * @hyetec
	 */
	public void setPkId(Long pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.user_id
	 *
	 * @return the value of f_enterprise.user_id
	 *
	 * @hyetec
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.user_id
	 *
	 * @param userId
	 *            the value for f_enterprise.user_id
	 *
	 * @hyetec
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.name
	 *
	 * @return the value of f_enterprise.name
	 *
	 * @hyetec
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.name
	 *
	 * @param name
	 *            the value for f_enterprise.name
	 *
	 * @hyetec
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.registered_capital
	 *
	 * @return the value of f_enterprise.registered_capital
	 *
	 * @hyetec
	 */
	public String getRegisteredCapital() {
		return registeredCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.registered_capital
	 *
	 * @param registeredCapital
	 *            the value for f_enterprise.registered_capital
	 *
	 * @hyetec
	 */
	public void setRegisteredCapital(String registeredCapital) {
		this.registeredCapital = registeredCapital == null ? null : registeredCapital.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.corporation
	 *
	 * @return the value of f_enterprise.corporation
	 *
	 * @hyetec
	 */
	public String getCorporation() {
		return corporation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.corporation
	 *
	 * @param corporation
	 *            the value for f_enterprise.corporation
	 *
	 * @hyetec
	 */
	public void setCorporation(String corporation) {
		this.corporation = corporation == null ? null : corporation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.address
	 *
	 * @return the value of f_enterprise.address
	 *
	 * @hyetec
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.address
	 *
	 * @param address
	 *            the value for f_enterprise.address
	 *
	 * @hyetec
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.permission
	 *
	 * @return the value of f_enterprise.permission
	 *
	 * @hyetec
	 */
	public Long getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.permission
	 *
	 * @param permission
	 *            the value for f_enterprise.permission
	 *
	 * @hyetec
	 */
	public void setPermission(Long permission) {
		this.permission = permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.introduction
	 *
	 * @return the value of f_enterprise.introduction
	 *
	 * @hyetec
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.introduction
	 *
	 * @param introduction
	 *            the value for f_enterprise.introduction
	 *
	 * @hyetec
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.brief
	 *
	 * @return the value of f_enterprise.brief
	 *
	 * @hyetec
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.brief
	 *
	 * @param brief
	 *            the value for f_enterprise.brief
	 *
	 * @hyetec
	 */
	public void setBrief(String brief) {
		this.brief = brief == null ? null : brief.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.level
	 *
	 * @return the value of f_enterprise.level
	 *
	 * @hyetec
	 */
	public Long getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.level
	 *
	 * @param level
	 *            the value for f_enterprise.level
	 *
	 * @hyetec
	 */
	public void setLevel(Long level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.status
	 *
	 * @return the value of f_enterprise.status
	 *
	 * @hyetec
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.status
	 *
	 * @param status
	 *            the value for f_enterprise.status
	 *
	 * @hyetec
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_enterprise.create_time
	 *
	 * @return the value of f_enterprise.create_time
	 *
	 * @hyetec
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_enterprise.create_time
	 *
	 * @param createTime
	 *            the value for f_enterprise.create_time
	 *
	 * @hyetec
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * f_enterprise
	 *
	 * @hyetec
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Enterprise other = (Enterprise) that;
		return (this.getPkId() == null ? other.getPkId() == null
				: this.getPkId().equals(other.getPkId()))
				&& (this.getUserId() == null ? other.getUserId() == null
						: this.getUserId().equals(other.getUserId()))
				&& (this.getName() == null ? other.getName() == null
						: this.getName().equals(other.getName()))
				&& (this.getRegisteredCapital() == null ? other.getRegisteredCapital() == null
						: this.getRegisteredCapital().equals(other.getRegisteredCapital()))
				&& (this.getCorporation() == null ? other.getCorporation() == null
						: this.getCorporation().equals(other.getCorporation()))
				&& (this.getAddress() == null ? other.getAddress() == null
						: this.getAddress().equals(other.getAddress()))
				&& (this.getPermission() == null ? other.getPermission() == null
						: this.getPermission().equals(other.getPermission()))
				&& (this.getIntroduction() == null ? other.getIntroduction() == null
						: this.getIntroduction().equals(other.getIntroduction()))
				&& (this.getBrief() == null ? other.getBrief() == null
						: this.getBrief().equals(other.getBrief()))
				&& (this.getLevel() == null ? other.getLevel() == null
						: this.getLevel().equals(other.getLevel()))
				&& (this.getStatus() == null ? other.getStatus() == null
						: this.getStatus().equals(other.getStatus()))
				&& (this.getCreateTime() == null ? other.getCreateTime() == null
						: this.getCreateTime().equals(other.getCreateTime()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * f_enterprise
	 *
	 * @hyetec
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getPkId() == null) ? 0 : getPkId().hashCode());
		result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
		result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
		result = prime * result
				+ ((getRegisteredCapital() == null) ? 0 : getRegisteredCapital().hashCode());
		result = prime * result + ((getCorporation() == null) ? 0 : getCorporation().hashCode());
		result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
		result = prime * result + ((getPermission() == null) ? 0 : getPermission().hashCode());
		result = prime * result + ((getIntroduction() == null) ? 0 : getIntroduction().hashCode());
		result = prime * result + ((getBrief() == null) ? 0 : getBrief().hashCode());
		result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
		result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * f_enterprise
	 *
	 * @hyetec
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pkId=").append(pkId);
		sb.append(", userId=").append(userId);
		sb.append(", name=").append(name);
		sb.append(", registeredCapital=").append(registeredCapital);
		sb.append(", corporation=").append(corporation);
		sb.append(", address=").append(address);
		sb.append(", permission=").append(permission);
		sb.append(", introduction=").append(introduction);
		sb.append(", brief=").append(brief);
		sb.append(", level=").append(level);
		sb.append(", status=").append(status);
		sb.append(", createTime=").append(createTime);
		sb.append("]");
		return sb.toString();
	}

	public String getCreditNumber() {
		return creditNumber;
	}

	public void setCreditNumber(String creditNumber) {
		this.creditNumber = creditNumber;
	}

	public String getListingCode() {
		return listingCode;
	}

	public void setListingCode(String listingCode) {
		this.listingCode = listingCode;
	}

	public Integer getTimes() {
		return times;
	}

	public void setTimes(Integer times) {
		this.times = times;
	}
}