/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.model;

import com.hyetec.uap.core.model.IdLong;
import java.util.Date;

public class Expert extends IdLong {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.pk_id
     *
     * @hyetec
     */
    private Long pkId;
    
    private Integer times;
    
    private Double score;

    public Double getScore() {
		return score;
	}

	public void setScore(Double score) {
		this.score = score;
	}

	public Integer getTimes() {
		return times;
	}

	public void setTimes(Integer times) {
		this.times = times;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.user_id
     *
     * @hyetec
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.company
     *
     * @hyetec
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.job
     *
     * @hyetec
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.special
     *
     * @hyetec
     */
    private String special;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.qualification
     *
     * @hyetec
     */
    private String qualification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.Category
     *
     * @hyetec
     */
    private Long category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.level
     *
     * @hyetec
     */
    private Long level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.introduction
     *
     * @hyetec
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.status
     *
     * @hyetec
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_expert.create_time
     *
     * @hyetec
     */
    private Date createTime;
    
    private String name;
    private String levelName;
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.pk_id
     *
     * @return the value of f_expert.pk_id
     *
     * @hyetec
     */
    public Long getPkId() {
        return pkId;
    }

    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLevelName() {
		return levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	public String getImgurl() {
		return imgurl;
	}

	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.pk_id
     *
     * @param pkId the value for f_expert.pk_id
     *
     * @hyetec
     */
    public void setPkId(Long pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.user_id
     *
     * @return the value of f_expert.user_id
     *
     * @hyetec
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.user_id
     *
     * @param userId the value for f_expert.user_id
     *
     * @hyetec
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.company
     *
     * @return the value of f_expert.company
     *
     * @hyetec
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.company
     *
     * @param company the value for f_expert.company
     *
     * @hyetec
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.job
     *
     * @return the value of f_expert.job
     *
     * @hyetec
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.job
     *
     * @param job the value for f_expert.job
     *
     * @hyetec
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.special
     *
     * @return the value of f_expert.special
     *
     * @hyetec
     */
    public String getSpecial() {
        return special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.special
     *
     * @param special the value for f_expert.special
     *
     * @hyetec
     */
    public void setSpecial(String special) {
        this.special = special == null ? null : special.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.qualification
     *
     * @return the value of f_expert.qualification
     *
     * @hyetec
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.qualification
     *
     * @param qualification the value for f_expert.qualification
     *
     * @hyetec
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.Category
     *
     * @return the value of f_expert.Category
     *
     * @hyetec
     */
    public Long getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.Category
     *
     * @param category the value for f_expert.Category
     *
     * @hyetec
     */
    public void setCategory(Long category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.level
     *
     * @return the value of f_expert.level
     *
     * @hyetec
     */
    public Long getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.level
     *
     * @param level the value for f_expert.level
     *
     * @hyetec
     */
    public void setLevel(Long level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.introduction
     *
     * @return the value of f_expert.introduction
     *
     * @hyetec
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.introduction
     *
     * @param introduction the value for f_expert.introduction
     *
     * @hyetec
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.status
     *
     * @return the value of f_expert.status
     *
     * @hyetec
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.status
     *
     * @param status the value for f_expert.status
     *
     * @hyetec
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_expert.create_time
     *
     * @return the value of f_expert.create_time
     *
     * @hyetec
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_expert.create_time
     *
     * @param createTime the value for f_expert.create_time
     *
     * @hyetec
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_expert
     *
     * @hyetec
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Expert other = (Expert) that;
        return (this.getPkId() == null ? other.getPkId() == null : this.getPkId().equals(other.getPkId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getJob() == null ? other.getJob() == null : this.getJob().equals(other.getJob()))
            && (this.getSpecial() == null ? other.getSpecial() == null : this.getSpecial().equals(other.getSpecial()))
            && (this.getQualification() == null ? other.getQualification() == null : this.getQualification().equals(other.getQualification()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getIntroduction() == null ? other.getIntroduction() == null : this.getIntroduction().equals(other.getIntroduction()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_expert
     *
     * @hyetec
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkId() == null) ? 0 : getPkId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getJob() == null) ? 0 : getJob().hashCode());
        result = prime * result + ((getSpecial() == null) ? 0 : getSpecial().hashCode());
        result = prime * result + ((getQualification() == null) ? 0 : getQualification().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getIntroduction() == null) ? 0 : getIntroduction().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_expert
     *
     * @hyetec
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkId=").append(pkId);
        sb.append(", userId=").append(userId);
        sb.append(", company=").append(company);
        sb.append(", job=").append(job);
        sb.append(", special=").append(special);
        sb.append(", qualification=").append(qualification);
        sb.append(", category=").append(category);
        sb.append(", level=").append(level);
        sb.append(", introduction=").append(introduction);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}