/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.model;

import com.hyetec.uap.core.model.IdLong;
import java.util.Date;

public class Inivestor extends IdLong {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.pk_id
     *
     * @hyetec
     */
    private Long pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.user_id
     *
     * @hyetec
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.company
     *
     * @hyetec
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.job
     *
     * @hyetec
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.special
     *
     * @hyetec
     */
    private String special;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.qualification
     *
     * @hyetec
     */
    private String qualification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.permission
     *
     * @hyetec
     */
    private Long permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.status
     *
     * @hyetec
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_inivestor.create_time
     *
     * @hyetec
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.pk_id
     *
     * @return the value of f_inivestor.pk_id
     *
     * @hyetec
     */
    public Long getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.pk_id
     *
     * @param pkId the value for f_inivestor.pk_id
     *
     * @hyetec
     */
    public void setPkId(Long pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.user_id
     *
     * @return the value of f_inivestor.user_id
     *
     * @hyetec
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.user_id
     *
     * @param userId the value for f_inivestor.user_id
     *
     * @hyetec
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.company
     *
     * @return the value of f_inivestor.company
     *
     * @hyetec
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.company
     *
     * @param company the value for f_inivestor.company
     *
     * @hyetec
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.job
     *
     * @return the value of f_inivestor.job
     *
     * @hyetec
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.job
     *
     * @param job the value for f_inivestor.job
     *
     * @hyetec
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.special
     *
     * @return the value of f_inivestor.special
     *
     * @hyetec
     */
    public String getSpecial() {
        return special;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.special
     *
     * @param special the value for f_inivestor.special
     *
     * @hyetec
     */
    public void setSpecial(String special) {
        this.special = special == null ? null : special.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.qualification
     *
     * @return the value of f_inivestor.qualification
     *
     * @hyetec
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.qualification
     *
     * @param qualification the value for f_inivestor.qualification
     *
     * @hyetec
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.permission
     *
     * @return the value of f_inivestor.permission
     *
     * @hyetec
     */
    public Long getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.permission
     *
     * @param permission the value for f_inivestor.permission
     *
     * @hyetec
     */
    public void setPermission(Long permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.status
     *
     * @return the value of f_inivestor.status
     *
     * @hyetec
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.status
     *
     * @param status the value for f_inivestor.status
     *
     * @hyetec
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_inivestor.create_time
     *
     * @return the value of f_inivestor.create_time
     *
     * @hyetec
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_inivestor.create_time
     *
     * @param createTime the value for f_inivestor.create_time
     *
     * @hyetec
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_inivestor
     *
     * @hyetec
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Inivestor other = (Inivestor) that;
        return (this.getPkId() == null ? other.getPkId() == null : this.getPkId().equals(other.getPkId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getJob() == null ? other.getJob() == null : this.getJob().equals(other.getJob()))
            && (this.getSpecial() == null ? other.getSpecial() == null : this.getSpecial().equals(other.getSpecial()))
            && (this.getQualification() == null ? other.getQualification() == null : this.getQualification().equals(other.getQualification()))
            && (this.getPermission() == null ? other.getPermission() == null : this.getPermission().equals(other.getPermission()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_inivestor
     *
     * @hyetec
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkId() == null) ? 0 : getPkId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getJob() == null) ? 0 : getJob().hashCode());
        result = prime * result + ((getSpecial() == null) ? 0 : getSpecial().hashCode());
        result = prime * result + ((getQualification() == null) ? 0 : getQualification().hashCode());
        result = prime * result + ((getPermission() == null) ? 0 : getPermission().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_inivestor
     *
     * @hyetec
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkId=").append(pkId);
        sb.append(", userId=").append(userId);
        sb.append(", company=").append(company);
        sb.append(", job=").append(job);
        sb.append(", special=").append(special);
        sb.append(", qualification=").append(qualification);
        sb.append(", permission=").append(permission);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}