/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.model;

import com.hyetec.uap.core.model.IdLong;
import java.util.Date;

public class RoadshowPerson extends IdLong {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.pk_id
     *
     * @hyetec
     */
    private Long pkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.roadshow_id
     *
     * @hyetec
     */
    private Long roadshowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.user_id
     *
     * @hyetec
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.start_time
     *
     * @hyetec
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.end_time
     *
     * @hyetec
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.is_public
     *
     * @hyetec
     */
    private Integer isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.content
     *
     * @hyetec
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.status
     *
     * @hyetec
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_roadshow_person.create_time
     *
     * @hyetec
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.pk_id
     *
     * @return the value of f_roadshow_person.pk_id
     *
     * @hyetec
     */
    public Long getPkId() {
        return pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.pk_id
     *
     * @param pkId the value for f_roadshow_person.pk_id
     *
     * @hyetec
     */
    public void setPkId(Long pkId) {
        this.pkId = pkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.roadshow_id
     *
     * @return the value of f_roadshow_person.roadshow_id
     *
     * @hyetec
     */
    public Long getRoadshowId() {
        return roadshowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.roadshow_id
     *
     * @param roadshowId the value for f_roadshow_person.roadshow_id
     *
     * @hyetec
     */
    public void setRoadshowId(Long roadshowId) {
        this.roadshowId = roadshowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.user_id
     *
     * @return the value of f_roadshow_person.user_id
     *
     * @hyetec
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.user_id
     *
     * @param userId the value for f_roadshow_person.user_id
     *
     * @hyetec
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.start_time
     *
     * @return the value of f_roadshow_person.start_time
     *
     * @hyetec
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.start_time
     *
     * @param startTime the value for f_roadshow_person.start_time
     *
     * @hyetec
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.end_time
     *
     * @return the value of f_roadshow_person.end_time
     *
     * @hyetec
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.end_time
     *
     * @param endTime the value for f_roadshow_person.end_time
     *
     * @hyetec
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.is_public
     *
     * @return the value of f_roadshow_person.is_public
     *
     * @hyetec
     */
    public Integer getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.is_public
     *
     * @param isPublic the value for f_roadshow_person.is_public
     *
     * @hyetec
     */
    public void setIsPublic(Integer isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.content
     *
     * @return the value of f_roadshow_person.content
     *
     * @hyetec
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.content
     *
     * @param content the value for f_roadshow_person.content
     *
     * @hyetec
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.status
     *
     * @return the value of f_roadshow_person.status
     *
     * @hyetec
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.status
     *
     * @param status the value for f_roadshow_person.status
     *
     * @hyetec
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_roadshow_person.create_time
     *
     * @return the value of f_roadshow_person.create_time
     *
     * @hyetec
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_roadshow_person.create_time
     *
     * @param createTime the value for f_roadshow_person.create_time
     *
     * @hyetec
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_roadshow_person
     *
     * @hyetec
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoadshowPerson other = (RoadshowPerson) that;
        return (this.getPkId() == null ? other.getPkId() == null : this.getPkId().equals(other.getPkId()))
            && (this.getRoadshowId() == null ? other.getRoadshowId() == null : this.getRoadshowId().equals(other.getRoadshowId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getIsPublic() == null ? other.getIsPublic() == null : this.getIsPublic().equals(other.getIsPublic()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_roadshow_person
     *
     * @hyetec
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkId() == null) ? 0 : getPkId().hashCode());
        result = prime * result + ((getRoadshowId() == null) ? 0 : getRoadshowId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getIsPublic() == null) ? 0 : getIsPublic().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_roadshow_person
     *
     * @hyetec
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkId=").append(pkId);
        sb.append(", roadshowId=").append(roadshowId);
        sb.append(", userId=").append(userId);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", isPublic=").append(isPublic);
        sb.append(", content=").append(content);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}