/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.model;

import java.util.Date;

import com.hyetec.uap.core.model.IdLong;

public class User extends IdLong {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.pk_id
	 *
	 * @hyetec
	 */
	private Long pkId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.login_name
	 *
	 * @hyetec
	 */
	private String loginName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.salt
	 *
	 * @hyetec
	 */
	private String salt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.password
	 *
	 * @hyetec
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.User_name
	 *
	 * @hyetec
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.job_num
	 *
	 * @hyetec
	 */
	private String jobNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.openid
	 *
	 * @hyetec
	 */
	private String openid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.Category
	 *
	 * @hyetec
	 */
	private Long category;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.reference
	 *
	 * @hyetec
	 */
	private String reference;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.mobile
	 *
	 * @hyetec
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.email
	 *
	 * @hyetec
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.phone
	 *
	 * @hyetec
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.identity_type
	 *
	 * @hyetec
	 */
	private Long identityType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.identity_num
	 *
	 * @hyetec
	 */
	private String identityNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.img
	 *
	 * @hyetec
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.address
	 *
	 * @hyetec
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.sex
	 *
	 * @hyetec
	 */
	private Long sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.status
	 *
	 * @hyetec
	 */
	private Integer status;
	
	private Integer checkStatus;
	
	private Integer oldStatus;

	public Integer getOldStatus() {
		return oldStatus;
	}

	public void setOldStatus(Integer oldStatus) {
		this.oldStatus = oldStatus;
	}

	public Integer getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * f_user.create_time
	 *
	 * @hyetec
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.pk_id
	 *
	 * @return the value of f_user.pk_id
	 *
	 * @hyetec
	 */
	public Long getPkId() {
		return pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.pk_id
	 *
	 * @param pkId
	 *            the value for f_user.pk_id
	 *
	 * @hyetec
	 */
	public void setPkId(Long pkId) {
		this.pkId = pkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.login_name
	 *
	 * @return the value of f_user.login_name
	 *
	 * @hyetec
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.login_name
	 *
	 * @param loginName
	 *            the value for f_user.login_name
	 *
	 * @hyetec
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName == null ? null : loginName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.salt
	 *
	 * @return the value of f_user.salt
	 *
	 * @hyetec
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.salt
	 *
	 * @param salt
	 *            the value for f_user.salt
	 *
	 * @hyetec
	 */
	public void setSalt(String salt) {
		this.salt = salt == null ? null : salt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.password
	 *
	 * @return the value of f_user.password
	 *
	 * @hyetec
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.password
	 *
	 * @param password
	 *            the value for f_user.password
	 *
	 * @hyetec
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.User_name
	 *
	 * @return the value of f_user.User_name
	 *
	 * @hyetec
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.User_name
	 *
	 * @param userName
	 *            the value for f_user.User_name
	 *
	 * @hyetec
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.job_num
	 *
	 * @return the value of f_user.job_num
	 *
	 * @hyetec
	 */
	public String getJobNum() {
		return jobNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.job_num
	 *
	 * @param jobNum
	 *            the value for f_user.job_num
	 *
	 * @hyetec
	 */
	public void setJobNum(String jobNum) {
		this.jobNum = jobNum == null ? null : jobNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.openid
	 *
	 * @return the value of f_user.openid
	 *
	 * @hyetec
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.openid
	 *
	 * @param openid
	 *            the value for f_user.openid
	 *
	 * @hyetec
	 */
	public void setOpenid(String openid) {
		this.openid = openid == null ? null : openid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.Category
	 *
	 * @return the value of f_user.Category
	 *
	 * @hyetec
	 */
	public Long getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.Category
	 *
	 * @param category
	 *            the value for f_user.Category
	 *
	 * @hyetec
	 */
	public void setCategory(Long category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.reference
	 *
	 * @return the value of f_user.reference
	 *
	 * @hyetec
	 */
	public String getReference() {
		return reference;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.reference
	 *
	 * @param reference
	 *            the value for f_user.reference
	 *
	 * @hyetec
	 */
	public void setReference(String reference) {
		this.reference = reference == null ? null : reference.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.mobile
	 *
	 * @return the value of f_user.mobile
	 *
	 * @hyetec
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.mobile
	 *
	 * @param mobile
	 *            the value for f_user.mobile
	 *
	 * @hyetec
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.email
	 *
	 * @return the value of f_user.email
	 *
	 * @hyetec
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.email
	 *
	 * @param email
	 *            the value for f_user.email
	 *
	 * @hyetec
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.phone
	 *
	 * @return the value of f_user.phone
	 *
	 * @hyetec
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.phone
	 *
	 * @param phone
	 *            the value for f_user.phone
	 *
	 * @hyetec
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.identity_type
	 *
	 * @return the value of f_user.identity_type
	 *
	 * @hyetec
	 */
	public Long getIdentityType() {
		return identityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.identity_type
	 *
	 * @param identityType
	 *            the value for f_user.identity_type
	 *
	 * @hyetec
	 */
	public void setIdentityType(Long identityType) {
		this.identityType = identityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.identity_num
	 *
	 * @return the value of f_user.identity_num
	 *
	 * @hyetec
	 */
	public String getIdentityNum() {
		return identityNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.identity_num
	 *
	 * @param identityNum
	 *            the value for f_user.identity_num
	 *
	 * @hyetec
	 */
	public void setIdentityNum(String identityNum) {
		this.identityNum = identityNum == null ? null : identityNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.img
	 *
	 * @return the value of f_user.img
	 *
	 * @hyetec
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.img
	 *
	 * @param img
	 *            the value for f_user.img
	 *
	 * @hyetec
	 */
	public void setImg(String img) {
		this.img = img == null ? null : img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.address
	 *
	 * @return the value of f_user.address
	 *
	 * @hyetec
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.address
	 *
	 * @param address
	 *            the value for f_user.address
	 *
	 * @hyetec
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.sex
	 *
	 * @return the value of f_user.sex
	 *
	 * @hyetec
	 */
	public Long getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.sex
	 *
	 * @param sex
	 *            the value for f_user.sex
	 *
	 * @hyetec
	 */
	public void setSex(Long sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.status
	 *
	 * @return the value of f_user.status
	 *
	 * @hyetec
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.status
	 *
	 * @param status
	 *            the value for f_user.status
	 *
	 * @hyetec
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database
	 * column f_user.create_time
	 *
	 * @return the value of f_user.create_time
	 *
	 * @hyetec
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database
	 * column f_user.create_time
	 *
	 * @param createTime
	 *            the value for f_user.create_time
	 *
	 * @hyetec
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((loginName == null) ? 0 : loginName.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (loginName == null) {
			if (other.loginName != null)
				return false;
		} else if (!loginName.equals(other.loginName))
			return false;
		return true;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * f_user
	 *
	 * @hyetec
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pkId=").append(pkId);
		sb.append(", loginName=").append(loginName);
		sb.append(", salt=").append(salt);
		sb.append(", password=").append(password);
		sb.append(", userName=").append(userName);
		sb.append(", jobNum=").append(jobNum);
		sb.append(", openid=").append(openid);
		sb.append(", category=").append(category);
		sb.append(", reference=").append(reference);
		sb.append(", mobile=").append(mobile);
		sb.append(", email=").append(email);
		sb.append(", phone=").append(phone);
		sb.append(", identityType=").append(identityType);
		sb.append(", identityNum=").append(identityNum);
		sb.append(", img=").append(img);
		sb.append(", address=").append(address);
		sb.append(", sex=").append(sex);
		sb.append(", status=").append(status);
		sb.append(", createTime=").append(createTime);
		sb.append("]");
		return sb.toString();
	}

	public String getCredentialsSalt() {
		return loginName + salt;
	}
}