/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.web.controller;

import com.hyetec.uap.core.web.JsonResponse;
import com.hyetec.uap.core.web.controller.BaseController;
import com.hyetec.uap.wechat.model.RoadshowPerson;
import com.hyetec.uap.wechat.service.RoadshowPersonService;
import com.hyetec.uap.wechat.vo.RoadshowPersonVo;
import java.util.List;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

@Controller
@RequestMapping("/roadshowPerson")
public class RoadshowPersonController extends BaseController<RoadshowPerson, RoadshowPersonVo> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_roadshow_person
     *
     * @hyetec
     */
    private RoadshowPersonService roadshowPersonService;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_roadshow_person
     *
     * @hyetec
     */
    public RoadshowPersonService getRoadshowPersonService() {
        return( RoadshowPersonService)baseService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_roadshow_person
     *
     * @hyetec
     */
    @Autowired
    public void setRoadshowPersonService(RoadshowPersonService roadshowPersonService) {
        super.setBaseService(roadshowPersonService )  ;
        this.roadshowPersonService= (RoadshowPersonService )baseService;
    }
}