/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.web.controller;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.alibaba.fastjson.JSON;
import com.hyetec.uap.core.web.controller.BaseController;
import com.hyetec.uap.wechat.model.Expert;
import com.hyetec.uap.wechat.model.Order;
import com.hyetec.uap.wechat.model.Scheduling;
import com.hyetec.uap.wechat.service.DictionaryService;
import com.hyetec.uap.wechat.service.OrderService;
import com.hyetec.uap.wechat.service.SchedulingService;
import com.hyetec.uap.wechat.vo.ExpertVo;
import com.hyetec.uap.wechat.vo.SchedulingVo;

@Controller
@RequestMapping("/scheduling")
public class SchedulingController extends BaseController<Scheduling, SchedulingVo> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_scheduling
     *
     * @hyetec
     */
    private SchedulingService schedulingService;
    @Autowired
    private DictionaryService dictionaryService;
    @Autowired 
    private OrderService orderService;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_scheduling
     *
     * @hyetec
     */
    public SchedulingService getSchedulingService() {
        return( SchedulingService)baseService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_scheduling
     *
     * @hyetec
     */
    @Autowired
    public void setSchedulingService(SchedulingService schedulingService) {
        super.setBaseService(schedulingService )  ;
        this.schedulingService= (SchedulingService )baseService;
    }
    @RequestMapping("/list/{expert_id}/{page}")
   	public String list(@PathVariable Long expert_id ,@PathVariable Long page , ExpertVo expertVo, HttpServletRequest req, HttpServletResponse res,
   			Model model) {
		model.addAttribute("expert_id", expert_id);
		
		model.addAttribute("expertVo", expertVo);
		model.addAttribute("page", page);
	
		return "/scheduling/list";
   }
    @ResponseBody
    @RequestMapping(value="/list.json")
    public SchedulingVo list(SchedulingVo schedulingVo){
    	schedulingService.selectAll(schedulingVo);
    	return schedulingVo;
    }
    @ResponseBody
    @RequestMapping(value="/del/{id}")
    public boolean del(@PathVariable Long id){
    	boolean tag = true;
    	try {
    		schedulingService.delByPkId(id);
		} catch (Exception e) {
			e.printStackTrace();
			tag = false;
		}
    	return tag;
    }
    @RequestMapping("/toAdd/{expert_id}")
   	public String add(@PathVariable Long expert_id,Model model,Scheduling scheduling) {
    	model.addAttribute("expert_id", expert_id);
    	return "/scheduling/form";
	}
    
    @RequestMapping("/find/{id}/{page}")
    public String findEnterprise(@PathVariable Long id,@PathVariable Long page,Model model, ExpertVo expertVo){
    	List<Order> orders = orderService.selectBySchedulingId(id);
		Scheduling scheduling = schedulingService.selectByPrimaryKey(id);
		model.addAttribute("scheduling", scheduling);
		model.addAttribute("orders", orders);
		model.addAttribute("expertVo", expertVo);
		model.addAttribute("page", page);
    	return "/scheduling/findEnterprise";
    }
    
    @ResponseBody
    @RequestMapping(value="/toAdd.json")
    public Boolean toAdd(String scheduling){
    	boolean tag = true;
    	try {
    		Scheduling schedulings = JSON.parseObject(scheduling, Scheduling.class);
    		schedulings.setCreateTime(new Date());
    		schedulings.setStatus(0);
    		schedulingService.insertSelective(schedulings);
		} catch (Exception e) {
			e.printStackTrace();
		}
    	return tag;
    }
    @RequestMapping("/toEdit/{id}/{expert_id}")
   	public String edit(@PathVariable Long id ,@PathVariable Long expert_id , Model model) {
    	Scheduling schedulings = schedulingService.selectByPrimaryKey(id);
    	model.addAttribute("expert_id", expert_id);
   		model.addAttribute("scheduling", schedulings);
   		return "/scheduling/form";
    }
    @ResponseBody
    @RequestMapping(value="/toEdit.json")
    public Boolean toEdit(String scheduling){
    	boolean tag = true;
    	try {
    		Scheduling schedulings = JSON.parseObject(scheduling, Scheduling.class);
    		schedulingService.updateByPrimaryKeySelective(schedulings);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
    	return  tag;
    }
}