/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.service.impl;

import com.google.common.collect.Lists;
import com.hyetec.uap.core.service.impl.BaseServiceImpl;
import com.hyetec.uap.core.web.JsonResponse;
import com.hyetec.uap.wechat.mapper.AdviceMapper;
import com.hyetec.uap.wechat.mapper.EnterpriseMapper;
import com.hyetec.uap.wechat.model.Advice;
import com.hyetec.uap.wechat.model.Enterprise;
import com.hyetec.uap.wechat.model.Expert;
import com.hyetec.uap.wechat.model.User;
import com.hyetec.uap.wechat.service.EnterpriseService;
import com.hyetec.uap.wechat.util.UserUtils;
import com.hyetec.uap.wechat.vo.AdviceVo;
import com.hyetec.uap.wechat.vo.AttachmentVo;
import com.hyetec.uap.wechat.vo.ChatRoomPersonVo;
import com.hyetec.uap.wechat.vo.ChatRoomRecordVo;
import com.hyetec.uap.wechat.vo.ChatRoomVo;
import com.hyetec.uap.wechat.vo.DictionaryVo;
import com.hyetec.uap.wechat.vo.EnterpriseVo;

import java.util.Date;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class EnterpriseServiceImpl extends BaseServiceImpl<Enterprise, EnterpriseVo> implements EnterpriseService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_enterprise
     *
     * @hyetec
     */
    private EnterpriseMapper enterpriseMapper;
    @Autowired
    private AdviceMapper adviceMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_enterprise
     *
     * @hyetec
     */
    public EnterpriseMapper getEnterpriseMapper() {
        return  ( EnterpriseMapper) baseMapper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_enterprise
     *
     * @hyetec
     */
    @Autowired
    public void setEnterpriseMapper(EnterpriseMapper enterpriseMapper) throws Exception {
        super.setBaseMapper(enterpriseMapper);
        this.enterpriseMapper=enterpriseMapper;
    }
    
    @Override
    public void insertEnterprise(Enterprise enterprise, List<Advice> advice) {
    	User user = UserUtils.getUser();
    	enterprise.setCreateTime(new Date());
    	enterprise.setStatus(0);
    	enterprise.setUserId(user.getPkId());
    	enterpriseMapper.insertSelective(enterprise);
		for (Advice advicee : advice) {
			advicee.setCreateTime(new Date());
			advicee.setEnterpriseId(enterprise.getPkId());
			advicee.setStatus(0);
			advicee.setUserId(user.getPkId());
			adviceMapper.insertSelective(advicee);
		}
		
	}

	@Override
	public void updateEnterprise(Enterprise enterprises, List<Advice> advice) {
		User user = UserUtils.getUser();
		enterpriseMapper.updateByPrimaryKeySelective(enterprises);
		adviceMapper.deleAdviceByenterpriseId(enterprises.getPkId());
		for (Advice advicee : advice) {
			advicee.setCreateTime(new Date());
			advicee.setEnterpriseId(enterprises.getPkId());
			advicee.setStatus(0);
			advicee.setUserId(user.getPkId());
			adviceMapper.insertSelective(advicee);
		}
		
	}

	@Override
	public void delByPkId(Long pkId) {
		enterpriseMapper.delByPkId(pkId);
		adviceMapper.deleAdviceByenterpriseId(pkId);
	}

	@Override
	public List<Enterprise> selectAllEnterprise() {
		// TODO Auto-generated method stub
		return enterpriseMapper.selectAllEnterprise();
	}

	@Override
	public String selectBody(Long body) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Enterprise> selectAllEnterpriseByname(String name) {
		// TODO Auto-generated method stub
		return enterpriseMapper.selectAllEnterpriseByname(name);
	}

	@Override
	public Enterprise findByUserId(Long userId) {
		
		// TODO Auto-generated method stub
		
		Enterprise enterprise = enterpriseMapper.selectEnterpriseByUserId(userId);
		
		return enterprise;
	}

	@Override
	public Enterprise selectByUserId(Long userId) {
		// TODO Auto-generated method stub
		return enterpriseMapper.selectByUserId(userId);
	}

	@Override
	public List<Enterprise> selectAllTj() {
		// TODO Auto-generated method stub
		return enterpriseMapper.selectAllTj();
	}
}