/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.service.impl;

import com.fasterxml.jackson.databind.annotation.JsonAppend.Attr;
import com.google.common.collect.Lists;
import com.hyetec.uap.core.service.impl.BaseServiceImpl;
import com.hyetec.uap.core.web.JsonResponse;
import com.hyetec.uap.wechat.mapper.EvaluateMapper;
import com.hyetec.uap.wechat.mapper.ExpertMapper;
import com.hyetec.uap.wechat.mapper.OrderMapper;
import com.hyetec.uap.wechat.model.Advice;
import com.hyetec.uap.wechat.model.Evaluate;
import com.hyetec.uap.wechat.model.Expert;
import com.hyetec.uap.wechat.model.ExpertMsg;
import com.hyetec.uap.wechat.model.Order;
import com.hyetec.uap.wechat.service.ExpertService;
import com.hyetec.uap.wechat.vo.AdviceVo;
import com.hyetec.uap.wechat.vo.AttachmentVo;
import com.hyetec.uap.wechat.vo.ChatRoomPersonVo;
import com.hyetec.uap.wechat.vo.ChatRoomRecordVo;
import com.hyetec.uap.wechat.vo.ChatRoomVo;
import com.hyetec.uap.wechat.vo.DictionaryVo;
import com.hyetec.uap.wechat.vo.EnterpriseVo;
import com.hyetec.uap.wechat.vo.EvaluateVo;
import com.hyetec.uap.wechat.vo.ExpertVo;

import java.util.Date;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ExpertServiceImpl extends BaseServiceImpl<Expert, ExpertVo> implements ExpertService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_expert
     *
     * @hyetec
     */
    private ExpertMapper expertMapper;
    @Autowired
    private EvaluateMapper evaluateMapper;
    @Autowired
    private OrderMapper orderMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_expert
     *
     * @hyetec
     */
    public ExpertMapper getExpertMapper() {
        return  ( ExpertMapper) baseMapper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_expert
     *
     * @hyetec
     */
    @Autowired
    public void setExpertMapper(ExpertMapper expertMapper) throws Exception {
        super.setBaseMapper(expertMapper);
        this.expertMapper=expertMapper;
    }

	@Override
	public void delByPkId(Long pkId) {
		expertMapper.delByPkId(pkId);
		
	}

	@Override
	public ExpertMsg selectByUserId(Long userId) {
		// TODO Auto-generated method stub
		return expertMapper.selectByUserId(userId);
	}

	@Override
	public Expert findByUserId(Long userId) {
		// TODO Auto-generated method stub
		
		Expert expert = expertMapper.selectExpertByUserId(userId);
		
		return expert;
	}

	@Override
	public Expert selectById(Long userId) {
		// TODO Auto-generated method stub
		return expertMapper.selectById(userId);
	}

	@Override
	public Expert selectExpert(Expert expert) {
		// TODO Auto-generated method stub
		return expertMapper.selectExpert(expert);
	}

	@Override
	public Expert selectByUser(Long userId) {
		// TODO Auto-generated method stub
		return expertMapper.selectByUser(userId);
	}

	@Override
	public List<Expert> selectByEnterprise(Long userId) {
		// TODO Auto-generated method stub
		return expertMapper.selectByEnterprise(userId);
	}

	@Override
	public List<Expert> expertEvaluationStatistics(List<Expert> experts) {
		// TODO Auto-generated method stub
		for (Expert expert : experts) {
			Evaluate evaluate = new Evaluate();
			evaluate.setToUserId(expert.getUserId());
			expert.setScore(evaluateMapper.selectAvg(evaluate).getScore());
			expert.setTimes(orderMapper.selectGzd(expert.getUserId()).getSortNum());
		}
		return experts;
	}

	@Override
	public List<Expert> selectAllTj() {
		// TODO Auto-generated method stub
		return expertMapper.selectAllTj();
	}

}