/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.vo;

import com.hyetec.uap.core.mybatis.plugin.Pagination;
import com.hyetec.uap.wechat.model.Enterprise;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EnterpriseVo extends Pagination<Enterprise> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_enterprise
     *
     * @hyetec
     */
    private static Logger logger = LoggerFactory.getLogger(EnterpriseVo.class);

    private Enterprise enterprise;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_enterprise
     *
     * @hyetec
     */
    public Enterprise getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_enterprise
     *
     * @hyetec
     */
    public void setEnterprise(Enterprise enterprise) {
        this.enterprise=enterprise;
    }
}