/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.vo;

import com.hyetec.uap.core.mybatis.plugin.Pagination;
import com.hyetec.uap.wechat.model.Expert;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ExpertVo extends Pagination<Expert> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_expert
     *
     * @hyetec
     */
    private static Logger logger = LoggerFactory.getLogger(ExpertVo.class);

    private Expert expert;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_expert
     *
     * @hyetec
     */
    public Expert getExpert() {
        return expert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_expert
     *
     * @hyetec
     */
    public void setExpert(Expert expert) {
        this.expert=expert;
    }
}