/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.vo;

import com.hyetec.uap.core.mybatis.plugin.Pagination;
import com.hyetec.uap.wechat.model.Inivestor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class InivestorVo extends Pagination<Inivestor> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_inivestor
     *
     * @hyetec
     */
    private static Logger logger = LoggerFactory.getLogger(InivestorVo.class);

    private Inivestor inivestor;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_inivestor
     *
     * @hyetec
     */
    public Inivestor getInivestor() {
        return inivestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_inivestor
     *
     * @hyetec
     */
    public void setInivestor(Inivestor inivestor) {
        this.inivestor=inivestor;
    }
}