/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.vo;

import com.hyetec.uap.core.mybatis.plugin.Pagination;
import com.hyetec.uap.wechat.model.Roadshow;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RoadshowVo extends Pagination<Roadshow> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_roadshow
     *
     * @hyetec
     */
    private static Logger logger = LoggerFactory.getLogger(RoadshowVo.class);

    private Roadshow roadshow;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_roadshow
     *
     * @hyetec
     */
    public Roadshow getRoadshow() {
        return roadshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_roadshow
     *
     * @hyetec
     */
    public void setRoadshow(Roadshow roadshow) {
        this.roadshow=roadshow;
    }
}