/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.vo;

import com.hyetec.uap.core.mybatis.plugin.Pagination;
import com.hyetec.uap.wechat.model.Scheduling;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SchedulingVo extends Pagination<Scheduling> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_scheduling
     *
     * @hyetec
     */
    private static Logger logger = LoggerFactory.getLogger(SchedulingVo.class);

    private Scheduling scheduling;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_scheduling
     *
     * @hyetec
     */
    public Scheduling getScheduling() {
        return scheduling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_scheduling
     *
     * @hyetec
     */
    public void setScheduling(Scheduling scheduling) {
        this.scheduling=scheduling;
    }
}