/*******************************************************************************
* Copyright (c) 2017 by Hyetec  Corporation all right reserved.
* 2017年11月20日 11:09
* 
*******************************************************************************/
package com.hyetec.uap.wechat.vo;

import com.hyetec.uap.core.mybatis.plugin.Pagination;
import com.hyetec.uap.wechat.model.User;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UserVo extends Pagination<User> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table f_user
     *
     * @hyetec
     */
    private static Logger logger = LoggerFactory.getLogger(UserVo.class);

    private User user;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @hyetec
     */
    public User getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_user
     *
     * @hyetec
     */
    public void setUser(User user) {
        this.user=user;
    }
}